blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/rloutrel/gnome-extension-template/discussions
    about: Ask questions and discuss usage in the project discussions.
